### PR TITLE
Add software architecture content and paths

### PR DESCRIPTION
**Pull request by rebekahlow-jy**
Added software architecture content and paths, and deployed at https://rebekahlow-jy.github.io/se-book/architecture/

### CODE REVIEW

**Comment by damithc** [comment]
Let me know when ready to merge.

**Comment by rebekahlow-jy** [comment]
Alright, this should be ready to merge!

**Comment by damithc** [comment]
Couple of images seem to have extra padding on top. Save the diagram only, not the entire slide.
image

**Comment by rebekahlow-jy** [comment]
The image padding issues should be fixed now! (:

**Pull request merged**
